global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'cross-chain-price-checker'

scrape_configs:
  - job_name: 'ccpc_api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
